### ISSUE TITLE
Error when using data extraction expression

### ISSUE THREAD

**Issue by leighmetzroth** [datalust/seq-input-healthcheck#36]
Setting up our Seq instance following [this guide](https://blog.datalust.co/simple-health-checks-for-any-url/) and I used the suggested `status` field as the data extraction expression and we got the below exception logged from the plugin itself (we're using the. We're using the `HealthChecks.UI.Client` nuget for formatting the response, so it definitely has a `status` property in the response JSON.

Switching it to use `@Properties` works.

```
System.IO.FileLoadException: Could not load file or assembly 'Serilog.Formatting.Compact.Reader, Version=3.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. Could not find or load a specific file. (0x80131621)
File name: 'Serilog.Formatting.Compact.Reader, Version=3.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'
 ---> System.IO.FileLoadException: Could not load file or assembly 'Serilog.Formatting.Compact.Reader, Version=3.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at SeqCli.Apps.AppLoader.OnAssemblyResolve(Object _, ResolveEventArgs e) in C:\projects\seqcli\src\SeqCli\Apps\AppLoader.cs:line 116
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at Seq.Input.HealthCheck.Data.JsonDataExtractor.<>c__DisplayClass3_0.<.ctor>b__1(JToken v)
   at Seq.Input.HealthCheck.Data.JsonDataExtractor.ExtractData(TextReader json) in C:\projects\seq-input-healthcheck\src\Seq.Input.HealthCheck\Data\JsonDataExtractor.cs:line 71
   at Seq.Input.HealthCheck.HttpHealthCheck.DownloadContent(Stream body, String contentType, Nullable`1 contentLength) in C:\projects\seq-input-healthcheck\src\Seq.Input.HealthCheck\HttpHealthCheck.cs:line 201
   at Seq.Input.HealthCheck.HttpHealthCheck.CheckNow(CancellationToken cancel) in C:\projects\seq-input-healthcheck\src\Seq.Input.HealthCheck\HttpHealthCheck.cs:line 90
```

**Comment by liammclennan** [comment]
Hi @leighmetzroth 

I've not been able to reproduce this problem yet. Can you please tell me which version of Seq you are using, which version of Seq.Input.Healthcheck and which operating system you are using? Or send a diagnostic report (from Settings > Diagnostics) to support@datalust.co.

**Comment by leighmetzroth** [comment]
Hi Liam,

We are running version `2023.4.10219` of Seq, which is hosted on an Azure VM running Windows Server 2019 Datacenter.

Sorry for the delayed reply, it's been a crazy few weeks for us.

**Comment by liammclennan** [comment]
Thanks for the update. Can you please update to the latest Seq and Seq.Input.HealthCheck?

**Comment by leighmetzroth** [comment]
We were already running the latest of `Seq.Input.HealthCheck` and I updated Seq this morning when I realised it was so far out of date. I just added a test health check instance with `status` as the data extraction expression and it worked.

FWIW, we are liking the full result with `@Properties` anyway; from here it's just for the benefit of other people consuming this.

**Comment by nblumhardt** [comment]
Excellent news; thanks for the follow-up, @leighmetzroth 👍
